
UART_RESPONDER_SRC_DIR := $(dir $(lastword $(MAKEFILE_LIST)))

ifneq (1,$(RULES))

UART_RESPONDER_JAR := uart_responder.jar
UART_RESPONDER_DEPS = $(OC_WB_IP_LIB) $(STD_PROTOCOL_IF_LIB) $(CHISELLIB_JAR) $(SV_BFMS_JAR)
UART_RESPONDER_JARS = $(UART_RESPONDER_JAR) $(UART_RESPONDER_DEPS)
UART_RESPONDER_SRC := \
	$(wildcard $(UART_RESPONDER_SRC_DIR)/uart_responder/*.scala)

else # Rules

$(UART_RESPONDER_JAR) : $(UART_RESPONDER_SRC) $(UART_RESPONDER_DEPS)
	$(Q)$(DO_CHISELC)

endif
